lab3_sa/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
# from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'lab3.views.home', name='home'),
    url(r'^graph/$', 'lab3.views.graph', name='graph'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    # url(r'^admin/', include(admin.site.urls)),
)

lab3/models.py
from django.db import models

# Create your models here.

lab3/views.py
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.http import HttpResponse
from django import forms

import lab3.controllers.main as controller


class GraphForm(forms.Form):
    graph_matrix = forms.CharField(widget=forms.Textarea())


class RecreateForm(forms.Form):
    x = forms.IntegerField(min_value=1, required=True)
    y = forms.IntegerField(min_value=1, required=True)


def valid_matrix(form):
    matrix_string = form.cleaned_data['graph_matrix'].replace('\n', ' ').replace('\r', '')
    row_strings = matrix_string.split(';')
    row_count = len(row_strings)
    if row_count < 1:
        return False
    else:
        for row in row_strings:
            if len(row.split()) != row_count:
                return False
    return True


def home(request):
    if request.method == 'GET':
        form = GraphForm(initial={'graph_matrix':
                                      '   0 -0.7    0    0 -0.8 -0.5    0    0    0;\n' +
                                      '-0.5    0    0  0.1 -0.2 -0.3    0 -0.2    0;\n' +
                                      '   0    0    0    0  0.5  0.2    0    0    0;\n' +
                                      '   0    0    0    0 -0.1    0    0    0    0;\n' +
                                      '   0    0    0    0    0    0    0    0    0;\n' +
                                      ' 0.1  0.2  0.6    0  0.2    0  0.7  0.1  0.3;\n' +
                                      '   0    0    0    0 -0.1    0    0    0  0.9;\n' +
                                      '   0    0  0.3  0.5    0    0    0    0    0;\n' +
                                      '   0    0  0.1  0.1    0    0    0    0    0'
                                  })
        return render_to_response('home.html', {'form': form}, context_instance=RequestContext(request))
    if request.method == 'POST':
        form = GraphForm(request.POST)
        if form.is_valid() and valid_matrix(form):
            return redirect(controller.build_request(form.cleaned_data['graph_matrix']))
        else:
            return HttpResponse(status=500)


def graph(request):
    if request.method == 'GET':
        graph_json, matrix, matrix_json, eig, cycles, stability = controller.get_graph(request)
        form = RecreateForm()
        return render_to_response('graph.html', {'nodes': graph_json['nodes'],
                                                 'edges': graph_json['links'],
                                                 'matrix_html': matrix,
                                                 'matrix_json': matrix_json,
                                                 'eigenvalues': eig,
                                                 'cycles': cycles,
                                                 'stability': stability,
                                                 'form': form},
                                  context_instance=RequestContext(request))
    if request.method == 'POST':
        form = RecreateForm(request.POST)
        if form.is_valid():
            matrix = request.GET.get('data')
            x = int(form.cleaned_data['x'])
            y = int(form.cleaned_data['y'])
            return redirect(controller.build_request(controller.edit_graph(matrix, x, y)))
        else:
            return HttpResponse(status=500)

lab3/templates/graph.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Graph model</title>

    <link rel="shortcut icon" type="image/png" href="{{STATIC_URL}}/favicon.ico"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/vis.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/graph.css">

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/validator.min.js"></script>
    <script src="{{ STATIC_URL }}js/vis.min.js"></script>
    <script src="{{ STATIC_URL }}js/graph.js"></script>
</head>
<body>
    <div id="graph-stable" class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2 well">
        <div class="col-xs-4">
            <h4>Stability in disturbance</h4>
            <img id="stab0"/>
        </div>
        <div class="col-xs-4">
            <h4>Stability in value</h4>
            <img id="stab1"/>
        </div>
        <div class="col-xs-4">
            <h4>Structure stability</h4>
            <img id="stab2"/>
        </div>
    </div>
    <div id="graph-canvas" class="col-xs-10 col-md-8 col-xs-offset-1 col-md-offset-2 well"></div>
    <div id="graph-data" class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2 well">
        <h3>Adjacency matrix:</h3>
        <p>{{ matrix_html|safe }}</p>
        <h3>Eigenvalues:</h3>
        <p>{{ eigenvalues|safe }}</p>
        <h3>Even cycles:</h3>
        <p>{{ cycles|safe }}</p>
    </div>
    <div id="graph-form" class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2 well">
        <h3>Remove edge</h3>
        <form class="form-horizontal" data-toggle="validator" role="form" method="post">
            {% csrf_token %}
            {% load widget_tweaks %}
            <div class="form-group">
                <label class="control-label col-sm-2" for="id_x">From:</label>
                <div class="col-sm-3">
                    {{ form.x|add_class:"form-control"|attr:"required" }}
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="id_y">To:</label>
                <div class="col-sm-3">
                    {{ form.y|add_class:"form-control"|attr:"required" }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-3">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>
    </div>
    <script type="text/javascript">
        buildGraph({{ nodes|safe }}, {{ edges|safe }}, {{ matrix_json }}, {{ stability|safe }});
    </script>
</body>
</html>

lab3/templates/home.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>SA_LAB_3</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/home.css">

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/validator.min.js"></script>
    <script src="{{ STATIC_URL }}js/home.js"></script>
</head>
<body>
    <div class="content-holder well col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
        <form class="form-horizontal" data-toggle="validator" role="form" method="post">
            {% csrf_token %}
            {% load widget_tweaks %}
            <div class="form-group">
                <label class="control-label col-sm-3" for="id_graph_matrix">Matrix:</label>
                <div class="col-sm-9">
                    {{ form.graph_matrix|add_class:"form-control"|attr:"required" }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>
    </div>
</body>
</html>